// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFByWXk6bLylOZmbnV9cJXB7XwmAFp6L8',
    appId: '1:996209474620:web:9fdd19d1bae20bdf36d739',
    messagingSenderId: '996209474620',
    projectId: 'login-4af00',
    authDomain: 'login-4af00.firebaseapp.com',
    storageBucket: 'login-4af00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx8KRCYK4jHHWBrvZ_YMW-JVI_i5R3PPU',
    appId: '1:996209474620:android:25d76cffbabac72f36d739',
    messagingSenderId: '996209474620',
    projectId: 'login-4af00',
    storageBucket: 'login-4af00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ7xtW5sI1gdoe0vTIfY4ivWsDEwUfTsQ',
    appId: '1:996209474620:ios:b9f6a9e66857f68436d739',
    messagingSenderId: '996209474620',
    projectId: 'login-4af00',
    storageBucket: 'login-4af00.appspot.com',
    iosBundleId: 'com.example.helloohoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ7xtW5sI1gdoe0vTIfY4ivWsDEwUfTsQ',
    appId: '1:996209474620:ios:175e1fe4998b47aa36d739',
    messagingSenderId: '996209474620',
    projectId: 'login-4af00',
    storageBucket: 'login-4af00.appspot.com',
    iosBundleId: 'com.example.helloohoney.RunnerTests',
  );
}
